defaults:
  - _self_
  - dataset
  - model
  - strategies
  - experiment: ewc

seed: 42

project_name: continual_learning
device: gpu
gpus: 0,1
fast_dev_run: false
logging_on: true
negatives_amount: 6

batch_size: 16  # number of audio files per batch
lr: 3e-4  # learning rate
max_epochs: 100
workers: 16
val_split: 0.1  # validation set proportion    
loss_type: 2  # training loss types. 1: MSE loss, 2: MSE and multi-resolution STFT loss
mse_weight: 10000  # weight of the MSE loss
clipping_val: 1.0  # gradient clipping value
patience: 3  # learning rate scheduler's patience
factor: 0.5  # learning rate reduction factor
